application: west-spy
version: 1
runtime: go
api_version: go1

env_variables:
  AWS_ACCESS_KEY_ID: 'XXXXXXXXXXXXXX'
  AWS_SECRET_ACCESS_KEY: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXX'

skip_files:
- ^tools
- ^(.*/)?.*~
- \.hg

inbound_services:
- warmup
- mail

builtins:
- datastore_admin: on
- deferred: on

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /\.well-known/keybase.txt
  static_files: static/keybase.txt
  upload: keybase\.txt

- url: /static
  static_dir: static

- url: /cron/.*
  script: _go_app
  login: admin

- url: /admin/.*
  script: _go_app
  login: admin

- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /~dustin/.*\.(css|js|png|pub)
  static_dir: static/dustin/

- url: /~dustin/
  script: _go_app

- url: /s3sign/
  script: _go_app

- url: /~dustin/.*\.html
  script: _go_app

- url: .*
  script: _go_app
  login: optional
